### 

@base = http://127.0.0.1:8000


### 

POST {{base}}/auth/authenticate HTTP/1.1

{
  "email": "taseen@gmail.com",
  "password": "plsletmeinok?"
}

> {%
	client.global.set("access_token", response.body.access_token)
%}


### 

POST {{base}}/stripe/rent-car HTTP/1.1
Authorization: Bearer {{access_token}}

{
  "car_id": "699c3e48c123958e7498dc55"
}
