### 

@base = http://127.0.0.1:8000


### 

POST {{base}}/auth/authenticate HTTP/1.1

{
  "email": "taseen@gmail.com",
  "password": "plsletmeinok?"
}

> {%
	client.global.set("access_token", response.body.access_token)
%}


### 

POST {{base}}/stripe/rent-car HTTP/1.1
Authorization: Bearer {{access_token}}

{
  "car_id": "69ac85a8261cebf9420e65b5"
}
